# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Yoga für groß und klein"
description: >- # this means to ignore newlines until "baseurl:"
  Elisa Yoga für groß und klein
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.elisayoga.at/" # the base hostname & protocol for your site, e.g. http://example.com
newsletter: "http://eepurl.com/iG65VQ"
impressum: {
  name: "Elisa Gritsch",
  email: "info@elisayoga.at",
  purpose: "Yoga Unterricht",
  address: {
    city: "1010 Wien",
    street: "Wollzeile 12/1/21"
  },
  uid: "ATU73953206"
}

# Build settings
theme: minima
plugins:
  - jekyll-feed

sections: {
  left: [
    {
      id: kalender, 
      alt: "Kalender"
    },
    {
      id: about, 
      alt: "Über mich"
    },
    {
      id: iyengar, 
      alt: "Iyengar"
    }
  ],
  right: [
    {
      id: newsletter, 
      alt: "Kalender"
    }
  ]
}

focal_points: [
  {
    title: "Stehhaltungen",
    asana: "Ardha Chandrasana",
    image: "image01039.png",
    description: "Im Iyengar Yoga bilden die Stehhaltungen die Grundlage für alle weiteren Yogahaltungen.
Stehhaltungen kräftigen die Beine, aktivieren den Kreislauf und stabilisieren die Stimmung."
  },
  {
    title: "Vorwärtsstreckungen",
    asana: "Parsvotanasana",
    image: "image01564.png",
    description: "Vorwärtsstreckungen dehnen den Rücken und die Beine, sie beruhigen die Gedanken und Gefühle."
  },
  {
    title: "Drehungen",
    asana: "Parivrtta Parsvakonasana",
    image: "image02280.png",
    description: "Drehungen rotieren den Körper um seine Wirbelsäule. Sie stärken und dehnen zugleich Bauch- und Rückenmuskeln und unterstützen die Verdauung."
  },
  {
    title: "Rückwärtsstreckungen",
    asana: "Urdhva Dhanurasana",
    image: "image00400.png",
    description: "Rückwärtsstreckungen öffnen den Brustkorb und dehnen den Bauch. Sie aktivieren den Kreislauf, machen wach und können helfen Depressionen zu lindern.
Die hier gezeigte Rückwärtsstreckung ist eine fortgeschrittene, es wird schrittweise darauf hingeführt."
  },
  {
    title: "Umkehrhaltungen",
    asana: "Adho Mukha Vrksasana",
    image: "image05498.png",
    description: "Umkehrhaltungen fördern die Durchblutung des Gehirns, aktivieren den Geist und wirken
ausgleichend auf die Psyche. Besonders wichtig sind dabei der Kopf- und der Schulterstand. Der
Schulterstand wird im Iyengar Yoga mit erhöhten Schultern geübt, damit die Halswirbelsäule
entlasten wird."
  },
  {
    title: "Regenerativ",
    asana: "Sirsasana aus dem Seil",
    image: "image06500.png",
    description: "Regenerierende Haltungen führen zu einer Erholung des Körpers und des Geistes. Diese entspannenden und öffnen den Haltungen eignen sich dazu, Atemübungen (pranayama) vorzubereiten."
  }
]

newsList: [
  {
    title: "Neue Klassen verfügbar",
    date: "12.1.2024",
    description: "Neue Klassen verfügbar - sehr kurz."
  },
  {
    title: "Klasse fällt aus",
    description: "Klasse fällt aus, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Klasse fällt aus, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum."
  },
  {
    date: "20.12.2023",
    description: "Ohne Titel - ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum."
  },
  {
    title: "Neue Klasse mit Susi",
    date: "5.1.2024"
  },
]

slider: [
  "image00289.jpeg", "image00400.jpeg", "image00735.jpeg"
]

collections:
  legal_pages:
    output: true
    permalink: /legal/:title

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
